# .github/workflows/ci.yml

# Name of the workflow
name: Build and Push Docker Image

#
# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx for more advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub using the secrets we created
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # 4. Build the Docker image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          # Tag the image with the username and repository name
          tags: sankavi16/todo-app:latest